gamepy/app_cart/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from app_cart.views import *

urlpatterns = [
    # re_path('cart/', CartView.as_view(), name='cart'),
    re_path('cart_page/', CartPageShow.as_view(), name='cart_page'),
    re_path('add_page/', AddPageCart.as_view(), name='add_page'),
    re_path('sub_page/', SubtractPageCart.as_view(), name='sub_page'),
    re_path('del_page/', DeletePageCart.as_view(), name='del_page'),

    # re_path('add_num_cart/', AddNumCart.as_view(), name='add_num'),

]

gamepy/app_commidity/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from app_commidity.views import *

urlpatterns = [
    re_path('index/', IndexShow.as_view(), name='index'),
    re_path('product/', ProductShow.as_view(), name='product'),
    re_path(r'^category/(\d+)$', Category.as_view(), name='category'),
    re_path('review/', ReviewShow.as_view(), name='review'),
    re_path('search/', Search.as_view(), name='search'),
    # re_path('ajax_review/', ReviewGet.as_view(), name='review_get'),
    # re_path('category/action/', Category.as_view(), name='action'),
    # # re_path(r"['category/(?P<action>[^/]+)/\\Z']", Category.as_view(), name='action'),
    # re_path(r'category/venture/', Category.as_view(), name='venture'),
    # re_path(r'category/single/', Category.as_view(), name='single'),
    # re_path(r'category/multiplayer/', Category.as_view(), name='multiplayer'),
    # re_path(r'category/drama/', Category.as_view(), name='drama'),
    # re_path(r'category/sports/', Category.as_view(), name='sports'),
    # re_path(r'category/horror/', Category.as_view(), name='horror'),

    # Action
    # Venture
    # Single
    # Multiplayer
    # Drama
    # Sports
    # Horror
]

gamepy/app_order/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from app_order.views import *

from django.urls import reverse
urlpatterns = [
    re_path('order_page', OrderDetail.as_view(), name='order_page'),
    re_path('order_show/', OrderShow.as_view(), name='order_show'),
    re_path(r'order_del/(\d+)$', DelOrder.as_view(), name='order_del'),
    re_path(r'order_info/(\d+)$', OrderLast.as_view(), name='order_info'),
    re_path(r'buy/(\d+)$', buy, name="buy"),  # 支付宝处理完成后回调的get请求路由

    # re_path(r'^order_buy/(\d+)$', Buy.as_view(), name="order_buy"),  # 支付宝处理完成后回调的get请求路由
    re_path('result/', pay_result),  # 支付宝处理完成后回调的get请求路由
    re_path('update_order/', update_order),  # 支付宝处理完成后回调的post请求路由

]

gamepy/app_user/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from app_user.views import *
from django.urls import reverse
urlpatterns = [
    re_path('login/', Login.as_view(), name='login'),
    re_path('register/', Register.as_view(), name='register'),
    re_path('xieyi/', XieyiShow.as_view(), name='xieyi'),
    re_path('change/', ChangePasswd.as_view(), name='change'),
    re_path('my_index/', MyIndexPasswd.as_view(), name='my_index'),
    re_path('logout/', Logout.as_view(), name='logout'),
]

gamepy/gamepy/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include(('app_user.urls', 'app_user'), namespace='app_user')),
    re_path('', include(('app_commidity.urls', 'app_commidity'), namespace='app_commidity')),
    re_path('', include(('app_order.urls', 'app_order'), namespace='app_order')),
    re_path('', include(('app_cart.urls', 'app_cart'), namespace='app_cart')),
    # path('', include('app_order.urls')),
]

gamepy/templates/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="">
    <meta name="author" content="">
	
    <title>Mobile Shop</title>
	
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
	
	<!-- Custom CSS -->
    <link rel="stylesheet" href="/static/css/style.css">
	
	
	<!-- Custom Fonts -->
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/fonts/font-slider.css" type="text/css">
	
	<!-- jQuery and Modernizr-->
	<script src="/static/js/jquery-2.1.1.js"></script>
	
	<!-- Core JavaScript Files -->  	 
    <script src="/static/js/bootstrap.min.js"></script>

    <script type="text/javascript">
        {#function a(){#}
        {##}
        {#           var form = $("<form method='post'></form>");#}
        {#            form.attr({"action":{% url "app_order:order_page" %}});#}
        {#            $("html").append(form);#}
            function show_confirm()
            {
            var r=confirm("确认提交订单");
            if (r==true)
              {
                  window.location.href='{% url "app_order:order_page" %}';

            }


            else
              {
              alert("未确认订单!");
              }
            }
    </script>
</head>
<body>
	{% include 'top.html' %}
    {% include 'header.html' %}
    {% include 'navigation.html' %}
	<!--//////////////////////////////////////////////////-->
	<!--///////////////////Cart Page//////////////////////-->
	<!--//////////////////////////////////////////////////-->

	<div id="page-content" class="single-page">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<ul class="breadcrumb">
						<li><a href="{%  url 'app_commidity:index' %}">主页</a></li>
						<li><a href="">购物车</a></li>
					</ul>
				</div>
			</div>
        {% if game_kind_num %}
            {% for i in game_kind_num %}
			<div class="row">
				<div class="product well">
					<div class="col-md-3">
						<div class="image">
							<a href="{%  url 'app_commidity:product' %}?i={{ i.sku_id.sku_id }}">
                                <img src="/static/media/{{ i.sku_id.commditypicture_set.all.0.comm_picture.name }}" />
                            </a>
						</div>
					</div>
					<div class="col-md-9">
						<div class="caption">
							<div class="name"><h3><a href="{%  url 'app_commidity:product' %}?i={{ i.sku_id.sku_id }}">{{ i.sku_id.sku_name }}</a></h3></div>
{#							<div class="info">#}
{#								<ul>#}
{#									<li>Brand: text</li>#}
{#									<li>ID: 0122222</li>#}
{#								</ul>#}
{#							</div>#}
							<div class="price">现价： {% widthratio i.sku_id.sku_discount 1 i.sku_id.sku_price %}<span>原价： {{ i.sku_id.sku_price }}</span></div>
							<label>数量: </label> <input id="number_{{ forloop.counter }}" class="form-inline quantity" type="text" value="{{ i.num }}">
{#                 两个按钮为实现 使用ajax            #}
                            <button  id="add_{{ forloop.counter }}" class="btn btn-2 ">添加</button>
                            <button  id="sub_{{ forloop.counter }}" class="btn btn-2 ">减少</button>
							<hr>

							<button  class="btn btn-default pull-right" id="del_{{ forloop.counter }}">删除</button>
{#                            #}
						</div>
					</div>
				</div>	
			</div>

            {% endfor %}


                <div class="row">
                    <div class="pricedetails">
                        <div class="col-md-4 col-md-offset-8">
                            <table>
    {#							<h6>Price Details</h6>#}
                                <tr>
                                    <td>原价</td>
                                    <td id="s_c_p">{{ sum_cart_price }} 元</td>
                                </tr>
                                <tr>
                                    <td>折扣</td>
                                    <td>-----</td>
                                </tr>
                                <tr>
                                    <td>省去</td>
                                    <td id="s_p">{{ save_price }}元</td>
                                </tr>
                                <tr style="border-top: 1px solid #333">
                                    <td><h5>共计</h5></td>
                                    <td id="d_p">{{ discout_price }}元</td>
                                </tr>
                            </table>
    {#                没有实现ajax 与是否购买的认证        #}

                            <center><input  onclick="show_confirm()" class="btn btn-1" value="购买"></center>



    {#					#}
                        </div>
                    </div>
                </div>
        {% for i in game_kind_num %}
                <script>
                         $('#add_'+{{ forloop.counter }}).click(
                    function(){

                        $.ajax({
                        url: {%   url 'app_cart:add_page' %} ,             //请求的url地址,
                        type:"post",        //请求的方式
                        async:false,        // 同步
                         data:{					//发送给后端的数据
                            {#obj : {{ i }};#}
                         obj_id : {{ i.num_id }},		//获得name为i1的标签值

                        {#i2: {{ }},		//获得name为i2的标签值#}
                    },
                            {#接受后端数据的函数#}
                            success: function (data) {
                        console.log(data)
                            $("#number_{{ forloop.counter }}").val(data.obj_num)

                            $("#s_c_p").text(data.sum_cart_price+"元")
                            $("#d_p").text(data.discout_price+"元")
                            $("#s_p").text(data.save_price+"元")
                            },

                    })


                    })
                         $('#del_{{ forloop.counter }}').click(
                    function(){

                        $.ajax({
                        url: {%   url 'app_cart:del_page' %} ,             //请求的url地址,
                        type:"post",        //请求的方式
                        {#async:false,        // 同步#}
                         data:{					//发送给后端的数据
                            {#obj : {{ i }};#}
                         obj_id : {{ i.num_id }},		//获得name为i1的标签值

                        {#i2: {{ }},		//获得name为i2的标签值#}
                    },
                            {#接受后端数据的函数#}
                            success: function (data) {
                            alert("您已删除商品");
                            window.location.href = {% url "app_cart:cart_page" %};
                            },
                    })
                    })



                         $('#sub_'+{{ forloop.counter }}).click(
                    function(){
                        $.ajax({
                        url: {%   url 'app_cart:sub_page' %} ,             //请求的url地址,
                        type:"post",        //请求的方式

                         data:{					//发送给后端的数据
                            {#obj : {{ i }};#}
                         obj_id : "{{ i.num_id }}",		//获得name为i1的标签值

                        {#i2: {{ }},		//获得name为i2的标签值#}
                    },
                            {#接受后端数据的函数#}
                            success: function (data) {
                        console.log(data)
                        $("#number_{{ forloop.counter }}").val(data.obj_num)
                                $("#s_c_p").text(data.sum_cart_price+"元")
                                $("#d_p").text(data.discout_price+"元")
                                $("#s_p").text(data.save_price+"元")
                            },

                    })
                    })
                </script>
        {% endfor %}
            {% else %}
            <h1><a class="btn-success btn" href="{% url 'app_commidity:index' %}" >快去找自己喜欢的！！！！！！！！！添加至购物车</a></h1>
{% endif %}



{#			<div class="row">#}
{#				<div class="col-md-4 col-md-offset-8 ">#}
{#					<center><a href="#" class="btn btn-1">Continue To Shopping</a></center>#}
{#				</div>#}
{#			</div>#}

		</div>
	</div>	
	{% include 'foot.html' %}
</body>
</html>
{#function show_confirm()#}
{#            {#}
{#            var r=confirm("确认提交订单");#}
{#            if (r==true)#}
{#              {#}
{#                $.ajax({#}
                        {#async: false,#}
{#                        async: false,#}
                        {#url: {%   url 'app_cart:add_cart' %} ,             //请求的url地址,#}
{#                        url: {% url "app_order:order_page" %} ,#}
{#                        type:"post",        //请求的方式#}
                        {#async:false,#}
{##}
{#                    success: function (data) {#}
{#                        obj.document.write(data.data);#}
{#                    },#}
{##}
{#                    }#}
{#                )#}
{##}
{##}
{#              }#}
{#            else#}
{#              {#}
{#              alert("未确认订单!");#}
{#              }#}
{#            }#}

gamepy/templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Mobile Shop</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">

	<!-- Custom CSS -->
    <link rel="stylesheet" href="/static/css/style.css">


	<!-- Custom Fonts -->
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/fonts/font-slider.css" type="text/css">

	<!-- jQuery and Modernizr-->
	<script src="/static/js/jquery-2.1.1.js"></script>

	<!-- Core JavaScript Files -->
    <script src="/static/js/bootstrap.min.js"></script>
    <style>
        .zoomImage{
            width:100%;
            height:0;
            padding-bottom: 70%;
            overflow:hidden;
            background-position: center center;
            background-repeat: no-repeat;
            -webkit-background-size:cover;
            -moz-background-size:cover;
            background-size:cover;
        }
    </style>


</head>
<body>
	{% include 'top.html' %}
    {% include 'header.html' %}
    {% include 'navigation.html' %}

	<!--//////////////////////////////////////////////////-->
	<!--///////////////////Category Page//////////////////-->
	<!--//////////////////////////////////////////////////-->
	<div id="page-content" class="single-page">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<ul class="breadcrumb">
						<li><a href="{%  url 'app_commidity:index' %}">主页</a></li>
						<li><a href="">{{ cate_name }}</a></li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div id="main-content" class="col-md-10">
					<div class="row">
						<div class="col-md-12">

                            <div class="products">
                                {% for i in posts.object_list %}

                                <div class="col-lg-6 col-md-6 col-xs-12">
									<div class="product">
{#                                        #}
{#										<div class="image"><a href="product.html"><img src="/static/images/iphone.png" /></a></div>#}
										<div class="zoomImage"><a class="cover" id="home_pro_id_{{ forloop.counter }}" href="{%  url 'app_commidity:product' %}?i={{ i.sku_id }}"><img src="/static/media/{{  i.commditypicture_set.all.0.comm_picture.name }}" /></a></div>
                                        <div class="buttons">
{#                                             {{ forloop.counter }}#}
											<button class="btn cart" id="home_show_{{ forloop.counter }}" ><span class="glyphicon glyphicon-shopping-cart"></span></button>
											<a class="btn wishlist" href="#"><span class="glyphicon glyphicon-heart"></span></a>
											<a class="btn compare" href="#"><span class="glyphicon glyphicon-transfer"></span></a>
										</div>
										<div class="caption">
											<div class="name"><h3><a href="{%  url 'app_commidity:product' %}?i={{ i.sku_id }}">{{ i.sku_name }}</a></h3></div>
											<div class="price">{{ "折扣" }}<span>{{i.sku_price}} </span></div>
											<div class="rating">销量{{ i.sku_slaes }}     库存 {{ i.sku_stock }}</div>
										</div>
									</div>
								</div>
                                    <script>
                         $('#home_show_{{ forloop.counter }}').click(
                    function(){

                        $.ajax({
                                {#async: false,#}
                                async: false,
                                {#url: {%   url 'app_cart:add_cart' %} ,             //请求的url地址,#}
                                url: {% url "app_cart:add_page" %} ,
                                type:"get",        //请求的方式
                                {#async:false,#}
                                 data:{					//发送给后端的数据
                                    {#obj : {{ i }};#}
                                 sku_id : {{ i.sku_id }},		//获得name为i1的标签值

                                {#i2: {{ }},		//获得name为i2的标签值#}
                                 },
                            success: function (data) {



                                $("#header_cart").text(data.cart_num)
                            },

                            }
                        )

                    });

    </script>
                                {% endfor %}
							</div>
						</div>
					</div>



					<div class="row text-center">

                        <span>

                            {% if posts.has_previous %}
                                <a href="?page={{ posts.previous_page_number }}">上一页</a>
                            {% endif %}
                        </span>
                        <span>
                                第 {{ posts.number }} 页
                        </span>
                        <span>
                            {% if posts.has_next %}
                                <a href="?page={{ posts.next_page_number }}">下一页</a>
                            {% endif %}
                        </span>

                        <span>

                                共 {{ posts.paginator.num_pages }} 页

                        </span>

                    </div>

				</div>
{#            {% include 'right.html' %}#}
			</div>
		</div>
	</div>
















{% include 'foot.html' %}

</body>


</html>

gamepy/templates/orders_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Mobile Shop</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">

	<!-- Custom CSS -->
    <link rel="stylesheet" href="/static/css/style.css">


	<!-- Custom Fonts -->
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/fonts/font-slider.css" type="text/css">

	<!-- jQuery and Modernizr-->
	<script src="/static/js/jquery-2.1.1.js"></script>

	<!-- Core JavaScript Files -->
    <script src="/static/js/bootstrap.min.js"></script>

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	{% include 'top.html' %}
    {% include 'header.html' %}
    {% include 'navigation.html' %}
    <div id="page-content" class="single-page">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<ul class="breadcrumb">
						<li><a href="{%  url 'app_commidity:index' %}">主页</a></li>
						<li><a href="">订单</a></li>
					</ul>
				</div>
			</div>
        {% block  detail%}
            {% for i in game_kind_num %}
			<div class="row">
				<div class="product well">
					<div class="col-md-3">
						<div class="image">
							<a href="{%  url 'app_commidity:product' %}?i={{ i.sku_id.sku_id }}">
                                <img src="/static/media/{{ i.sku_id.commditypicture_set.all.0.comm_picture.name }}" />
                            </a>
						</div>
					</div>
					<div class="col-md-9">
						<div class="caption">
							<div class="name"><h3><a href="{%  url 'app_commidity:product' %}?i={{ i.sku_id.sku_id }}">{{ i.sku_id.sku_name }}</a></h3></div>

{#                            订单编号#}
                            {#							<div class="info">#}
                            {#								<ul>#}
                            {#									<li>Brand: text</li>#}
                            {#									<li>ID: 0122222</li>#}
                            {#								</ul>#}
                            {#							</div>#}
							<div class="price">现价： {% widthratio i.sku_id.sku_discount 1 i.sku_id.sku_price %}</div>
							<label>数量: {{ i.num }}</label>

							<hr>



						</div>
					</div>
				</div>
			</div>

            {% endfor %}


{% endblock %}

    <div class="row">
                    <div class="pricedetails">
                        <div class="col-md-4 col-md-offset-8">
                            <table>
                                <tr style="border-top: 1px solid #333">
                                    <td><h5>共计</h5></td>
                                    <td id="d_p">{{ information.order_all_number }}个</td>
                                    <td id="d_p">{{ information.order_all_money }}元</td>
                                </tr>
                            </table>
                            {% block  lk %}

{#                            <center><input onclick="show_confirm()" class="btn btn-1" value="购买"></center>#}
{##}
{#                            <a href="{% url "app_order:order_del" information.order_id %}">取消订单</a>#}
                                <form method="post" action="/order_buy/{{ information.order_id}}">
        <input type="hidden" name="ord_id" value={{ information.order_id }}>

<center><input type="submit" class="btn btn-1" value="购买"></center>

{#    <center><a href="{% url "app_order:buy" %}" class="btn btn-1" >购买</a></center>#}
</form>
        <a href="{% url "app_order:order_del" information.order_id %}">取消订单</a>
                            {% endblock %}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    {% include 'foot.html' %}

</body>
</html>

gamepy/templates/pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="" method="post">
    <input type="text" name="price">
    <input type="submit" value="去支付">
</form>

</body>
</html>

gamepy/templates/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="">
    <meta name="author" content="">
	
    <title>Mobile Shop</title>
	
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
	
	<!-- Custom CSS -->
    <link rel="stylesheet" href="/static/css/style.css">
	
	
	<!-- Custom Fonts -->
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/fonts/font-slider.css" type="text/css">
	
	<!-- jQuery and Modernizr-->
	<script src="/static/js/jquery-2.1.1.js"></script>
	
	<!-- Core JavaScript Files -->  	 
    <script src="/static/js/bootstrap.min.js"></script>
    
    <script src="/static/js/photo-gallery.js"></script>
	
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="/static/js/html5shiv.js"></script>
        <script src="/static/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	{% include 'top.html' %}
    {% include 'header.html' %}
    {% include 'navigation.html' %}
	<!--//////////////////////////////////////////////////-->
	<!--///////////////////Product Page///////////////////-->
	<!--//////////////////////////////////////////////////-->
	<div id="page-content" class="single-page">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<ul class="breadcrumb">
                        <li><a href="{%  url 'app_commidity:index' %}">主页</a></li>
						<li><a href="/category/{{  obj.com_id.com_id }}">{{ obj.com_id.com_name }}</a></li>
						<li><a href="">{{  obj.sku_name  }}</a></li>
					</ul>
				</div>
			</div>

			<div class="row">
				<div id="main-content" class="col-md-12">
					<div class="product">
						<div class="col-md-6">
							<div class="image">
								<img src="/static/media/{{ obj.commditypicture_set.all.0.comm_picture.name }}" id="tot"/>
								<div class="image-more">
									 <ul class="row">
                                         {% for j in obj.commditypicture_set.all %}
										 <li class="col-lg-3 col-sm-3 col-xs-4" >
{#                                             i.commditypicture_set.all.0.comm_picture.name#}
											<button id="pic_{{ forloop.counter }}" ><img class="img-responsive" src="/static/media/{{ j.comm_picture.name}}"></button>
										</li>
                                        <script>
                                     $('#pic_{{ forloop.counter }}').click(
                                                function(){
                                                   $('#tot').attr('src','/static/media/{{ j.comm_picture.name}}')
                                                });
                                              </script>
                                         {% endfor %}

									</ul>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="caption">
								<div class="name"><h2>{{ obj.sku_name }}</h2></div>
								<div class="info">
									<ul>
										<li>销量: {{ obj.sku_slaes }}</li>
										<li>库存: {{ obj.sku_stock }}</li>
									</ul>
								</div>
								<div class="price">{% widthratio obj.sku_discount 1 obj.sku_price %}<span>{{ obj.sku_price }}</span></div>
{#								<div class="options">#}
{#									AVAILABLE OPTIONS#}
{#									<select>#}
{#										<option value="" selected>----Please Select----</option>#}
{#										<option value="red">RED</option>#}
{#										<option value="black">BLACK</option>#}
{#									</select>#}
{#								</div>#}
								<div class="rating"><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star-empty"></span></div>
								<div class="well"><label>数量: </label> <input class="form-inline quantity" type="text" value="1"><button class="btn btn-2 " id="add" >增加</button></div>

                                <script>
                         $('#add').click(
                    function(){

                        $.ajax({
                                {#async: false,#}
                                async: false,
                                {#url: {%   url 'app_cart:add_cart' %} ,             //请求的url地址,#}
                                url: {% url "app_cart:add_page" %} ,
                                type:"get",        //请求的方式
                                {#async:false,#}
                                 data:{					//发送给后端的数据
                                    {#obj : {{ i }};#}
                                 sku_id : {{ obj.sku_id }},		//获得name为i1的标签值

                                {#i2: {{ }},		//获得name为i2的标签值#}
                                 },
                            success: function (data) {
                                     alert("添加成功");
                                $("#header_cart").text(data.cart_num)
                            },
                            }
                        )
                    });
    </script>




                                <div class="share well">
									<strong style="margin-right: 13px;">Share :</strong>
									<a href="" class="share-btn" target="_blank">
										<i class="fa fa-twitter"></i>
									</a>
									<a href="" class="share-btn" target="_blank">
										<i class="fa fa-facebook"></i>
									</a>
									<a href="" class="share-btn" target="_blank">
										<i class="fa fa-linkedin"></i>
									</a>
								</div>
							</div>
						</div>
						<div class="clear"></div>
					</div>	
					<div class="product-desc">
						<ul class="nav nav-tabs">
							<li class="active"><a href="{% url "app_commidity:product"  %}?i={{ obj.sku_id }}">简介</a></li>
							<li ><a href="{% url "app_commidity:review"  %}?i={{ obj.sku_id }}">评论</a></li>
						</ul>
                        {% block review %}
						<div class="tab-content">
                            {{ obj.sku_brief_introduction }}
						</div>
                        {% endblock %}
					</div>

				</div>
			</div>
		</div>
	</div>





    {% include 'foot.html' %}
	
{#	<!-- IMG-thumb -->#}
{#	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">#}
{#      <div class="modal-dialog">#}
{#        <div class="modal-content">         #}
{#          <div class="modal-body">                #}
{#          </div>#}
{#        </div><!-- /.modal-content -->#}
{#      </div><!-- /.modal-dialog -->#}
{#    </div><!-- /.modal -->#}
	
	<script>
	$(document).ready(function(){
		$(".nav-tabs a").click(function(){
			$(this).tab('show');
		});
		$('.nav-tabs a').on('shown.bs.tab', function(event){
			var x = $(event.target).text();         // active tab
			var y = $(event.relatedTarget).text();  // previous tab
			$(".act span").text(x);
			$(".prev span").text(y);
		});
	});
	</script>
</body>
</html>